### ISSUE TITLE
Website should be served through SSL

### ISSUE THREAD

**Issue by andreagrandi** [PyconUK/2016.pyconuk.org#105]
GitHub has recently introduced SSL for all GH pages: https://help.github.com/articles/securing-your-github-pages-site-with-https/

Can we have a look and see if it's possible to enable for PyCon UK website? I'm sure we can for generic pages but I'm not sure if we can when we use a custom domain.

Cheers

**Comment by kragniz** [comment]
From the docs: 

```
HTTPS is not supported for GitHub Pages using custom domains.
```

**Comment by andreagrandi** [comment]
@kragniz ouch :(

**Comment by meshy** [comment]
Perhaps this could be done with cloudflare?

**Comment by andreagrandi** [comment]
@meshy I was thinking about it (I use that too on my personal website). If it's not too complicated (I don't want to take precious time to the PyCon organisers) that could work well.

**Comment by ghickman** [comment]
@meshy @andreagrandi – IIRC CloudFlare requires you use them for DNS on the free plan?  If that's the case we'd have to make sure they support the DNS level URL redirects as that's how we deal with sending both www.pyconuk.org and pyconuk.org to the appropriate year subdomain (and thus the right GitHub project).

However, that being said, I'm not keen on changing the DNS setup now that we're "open for business" and actively marketing the conference.  It's certainly something we could look into for next year.

**Comment by meshy** [comment]
> we'd have to make sure they support the DNS level URL redirects

IIRC cloudflare do not support this.

> I'm not keen on changing the DNS setup now that we're "open for business" 

That makes perfect sense to me

**Comment by zeth** [comment]
On 29 June 2016 at 13:48, George Hickman <notifications@github.com> wrote:

> @meshy <https://github.com/meshy> @andreagrandi
> <https://github.com/andreagrandi> – IIRC CloudFlare requires you use them
> for DNS on the free plan? If that's the case we'd have to make sure they
> support the DNS level URL redirects as that's how we deal with sending both
> www.pyconuk.org and pyconuk.org to the appropriate year subdomain (and
> thus the right GitHub project).
>

I have just been playing with CloudFlare and for what its worth, I think it
would work. You do seem to get control over individual subdomains.

**Comment by Lukasa** [comment]
Given that the website is static, there's another option which is to do what I'm now doing for `lukasa.co.uk`: host the website using S3 and CloudFront. That also requires moving the DNS to Route53, but that would be fine by me because Route53 is excellent.

Of course, none of this is free (I end up paying around $2.50/mo for serving an average of 4k req/mo) but it needn't be that expensive either, and has the advantage of being pretty resilient (if we don't use US-East-1).

Anyway, worth considering as well: Cloudflare is good but the big long list of extra domains you get in your certs may not be a look PyCon UK wants very much, and ACM is a good replacement for Cloudflare's free TLS plans.

**Comment by zeth** [comment]
On 7 March 2017 at 08:16, Cory Benfield <notifications@github.com> wrote:

> Given that the website is static, there's another option which is to do
> what I'm now doing for lukasa.co.uk: host the website using S3 and
> CloudFront. That also requires moving the DNS to Route53, but that would be
> fine by me because Route53 is excellent.
>
> Of course, none of this is free (I end up paying around $2.50/mo for
> serving an average of 4k req/mo) but it needn't be that expensive either,
> and has the advantage of being pretty resilient (if we don't use US-East-1).
>
> Anyway, worth considering as well: Cloudflare is good but the big long
> list of extra domains you get in your certs may not be a look PyCon UK
> wants very much, and ACM is a good replacement for Cloudflare's free TLS
> plans.
>
>
Yeah to get our own certificate with Cloudfare costs $5 per month, the free
plan is a "Universal certificate" for every site on the IP, which is more
expensive than your setup (although not traffic restricted).

The best option may just be to wait it out and ignore HTTPS until github
come up with something for custom domains.
