### ISSUE TITLE
Page layout is weirdly warped on mobile

### ISSUE THREAD

**Issue by alexwlchan** [PyconUK/2016.pyconuk.org#151]
Viewing the homepage on an iPhone:

![img_8606](https://cloud.githubusercontent.com/assets/301220/17860036/df5ce816-6883-11e6-83d0-21a78f5a4178.PNG)

No margin on the left, text disappears off to the right.

I suspect this is the sponsor logos causing the page width to grow. I think I could have a stab at fixing this, but not before I get home from work.

**Comment by inglesp** [comment]
Hi @alexwlchan -- thanks for spotting this.  I'm afraid I only know enough CSS to be dangerous, and I took the HTML for this from last year's site, so I'd appreciate it if you could have a go!

**Comment by alexwlchan** [comment]
Ah. Turns out that `.intro` and `.content` both have fixed widths of `42.5em`, so they never resize, sponsors or otherwise. Will fix later.

**Comment by hawkz** [comment]
Doh, my bad, maybe should have been max-width, did this in a rush.

**Comment by alexwlchan** [comment]
Tweaks to fix this are in #152.

**Comment by alexwlchan** [comment]
Closing as #152 has been merged, and the site now looks pretty good. Remaining quirks should get their own issue.
