### ISSUE TITLE
Page title fonts look wrong on Chromium 49.0.2623.108 running on Ubuntu 15.10 (64-bit)

### ISSUE THREAD

**Issue by inglesp** [PyconUK/2016.pyconuk.org#20]
Reported by @snim2.

![](https://cloud.githubusercontent.com/assets/97674/14795725/b1292f00-0b21-11e6-881e-e7d2a78a108f.png)

**Comment by inglesp** [comment]
@snim2, when you look at the network tab in developer tools, do you see any resources failing to load?

**Comment by snim2** [comment]
I think @hawkz may have answered this elsewhere, but this was the resource:

https://use.typekit.net/c/9762e0/1w;futura-pt,7cdcb44be4a7db8877ffa5c0007b8dd865b3bbc383831fe2ea177f62257a9191,SH3:W:n5/l?3bb2a6e53c9684ffdc9a9bf1135b2a62ecbeaca761fbe87f15aec165ea5b93cbb6274cda3791f5b2541785b1009edc3cf681d3513a4f562377a89404231e440ae7d87063f9afd495a6c35400cf754d222cc3d29812d6a2c27b0240a62015ac885f88c0bc21310fb15950a1ee5ef677a235f44f92673528963aaee3a1e518f61801780f22c2121f0157ef87561e6e4410e6e52a9723d944b08e1676f24de20f02400a30db858464d5c6b2ed1e1394368ba553f0

**Comment by inglesp** [comment]
@hawkz says "The font will work on 127.0.0.1 and the live domain. It's a licensing thing. I'll try to add 0.0.0.0".

@snim2, can you confirm that http://2016.pyconuk.org/home/ looks OK?

**Comment by snim2** [comment]
That makes no difference to me, I get an error called `Failed to load resource: net::ERR_BLOCKED_BY_CLIENT` on this resource: 

https://p.typekit.net/p.gif?s=1&k=kla0hed&app=typekit&ht=tk&h=2016.pyconuk.org&f=10879&a=146498&sl=680&fl=23&dc=true&js=1.14.9&_=1461658364552

**Comment by inglesp** [comment]
@snim2, could it be the case that you're running some third-party script blocker that's causing the client to not load the resource?

@hawkz, would licencing cause the `ERR_BLOCKED_BY_CLIENT` error?

**Comment by ghickman** [comment]
Paging @meshy as another Linux user.

**Comment by snim2** [comment]
Ha! Well, this is rather embarrassing. If I turn my ad blocker off the error in the dev. tools pane disappears, but the fonts still overlap. I think perhaps I am overriding all the fonts in my Chromium settings. In FireFox it looks a little better, and I think the two browsers use the same rendering engine:

![snim2-ff](https://cloud.githubusercontent.com/assets/97674/14811809/d5b59dd4-0b91-11e6-8776-c107f0ee54b3.png)

**Comment by Lukasa** [comment]
Firefox and Chrome use different rendering engines.

**Comment by inglesp** [comment]
OK!  So we should have some kind of fallback in case fonts can't be loaded, but I don't think this is a blocker for launching today.

**Comment by inglesp** [comment]
@snim2, is this now the same issue as https://github.com/PyconUK/2016.pyconuk.org/issues/40?

**Comment by snim2** [comment]
Nope, my "Tickets" and "Contact" are nicely separated out. Even if I resize my browser I can't reproduce #40 in Chromium.

**Comment by inglesp** [comment]
OK -- I'm not clear on what the problem is then.  (I'm probably being dense.)  Which are the fonts that overlap?

**Comment by hawkz** [comment]
The font we use at PyConUK isn't free (because the classic ones generally aren't) Typekit hosts it and blocks requests from other domains. I've added 0.0.0.0 to the list of whitelisted domains - might fix your local test now. 

The list is now: "pyconuk.org, _.pyconuk.org, pyconuk.net,_.pyconuk.net, localhost, 127.0.0.1, 192.168.2.250, 0.0.0.0"

**Comment by hawkz** [comment]
can we get a re-test, think this is cleared, I'll add a better fall-back as per #51 to handle this better. (It's the difference in glyph width that's throwing off the spacing)

**Comment by inglesp** [comment]
Assigning to @snim2 to test.

**Comment by snim2** [comment]
This is `/home/` on `0.0.0.0:8000`:

![snim2-0000](https://cloud.githubusercontent.com/assets/97674/14846046/a0d78cb2-0c59-11e6-84cb-a6dbf92ee158.png)

This is `/home/` on the live site:

![snim2-live](https://cloud.githubusercontent.com/assets/97674/14846052/a996d7d6-0c59-11e6-986e-d971fa17995d.png)

**Comment by inglesp** [comment]
@snim2 A bit late, but is this fixed?

**Comment by snim2** [comment]
Yes, all looks good to me, thanks!
