### ISSUE TITLE
Deployment can fail but Travis reports success

### ISSUE THREAD

**Issue by inglesp** [PyconUK/2016.pyconuk.org#21]
See https://travis-ci.org/PyconUK/2016.pyconuk.org/builds/125716205 for an example.

The failure output is

```
remote: Invalid username or password.
fatal: Authentication failed for 'https://PyConUK-user@github.com/PyconUK/2016.pyconuk.org/'
make: *** [deploy] Error 128
```

**Comment by inglesp** [comment]
Running `deploy.sh` from the command line succeeds, so this is not urgent to fix.

@ghickman, could you take a look when you get the chance?  (Or assign to @meshy?)

**Comment by ghickman** [comment]
@inglesp – shoot, I know exactly what this is. The `GH_TOKEN` variable isn't set, I'll fix now. Sorry about that!

**Comment by ghickman** [comment]
@inglesp – fixed and PR for docs at PyconUK/pyconuk-2016-internaldocs#61
