### ISSUE TITLE
Create a wishlist for design for post-conference / next year.

### ISSUE THREAD

**Issue by hawkz** [PyconUK/2016.pyconuk.org#291]
To help the process, could we compile a list of things needing design?
Like #63 

Do we need any post-conference design, and should we be doing new design / advertising next years conference. (Really trying hard to get away from the last minute stuff / more notice, so I can contribute more)

**Comment by inglesp** [comment]
Hi @hawkz 

We haven't quite finished putting 2016 to bed yet!  Can we come back to this in the new year?

**Comment by hawkz** [comment]
Sure. I keep trying, would be great to get 1 year ahead.. we _know_ we're going to do it...
