### ISSUE TITLE
Decide on global navigation headings

### ISSUE THREAD

**Issue by inglesp** [PyconUK/2016.pyconuk.org#3]
There are more pages on the site than space in the global navbar, so we need to decide what we include.

For now, we need to have at least:
- CFP
- Registration
- Code of Conduct
- Sponsorship
- Contact

These can change -- for instance, the CFP could become Programme once the CFP closes, and we could drop the Registration link once we've sold all the tickets.

Others:
- Venue
- Diversity & Accessibility
- News
- Speaker mentors
- Education
- Science

I think some of these don't belong in the global navbar, but could be linked to from the text of the front page.

I'm sure @evildmp will have thoughts.

**Comment by hawkz** [comment]
All I need at this stage is the longest title and the largest quantity so I can sort the responsive nav out.

**Comment by inglesp** [comment]
I think we should have:
- Call For Proposals
- Tickets
- Code of Conduct
- Sponsorship
- Contact
- News

Everything else can be linked to from copy on the homepage.

**Comment by kragniz** [comment]
Maybe switch news for venue? Whenever I tell someone about it, the first question people seem to ask me is where it will be held.

**Comment by inglesp** [comment]
That's a good observation @kragniz.  However, we mention the venue in the first paragraph on the homepage which should be enough for anyone who wants to know where the conference is.

When the conference is running, people will need information about where to find things.  At this point, we'll probably want to get rid of the "Tickets" link, since tickets will have all been sold, and can replace it with the "Venue" link.

**Comment by snim2** [comment]
Can I suggest we put "news" on the front page, where it is most visible? IMO this would be better for news like "we are closing the CFP real soon now..."

If we did have a venue heading, as @kragniz suggests, it could include useful information like local choices for accommodation, which might be useful for delegate before they book.

**Comment by inglesp** [comment]
News on the front page sounds sensible.

So, @hawkz, we'll want:
- Tickets
- Call For Proposals
- Sponsorship
- Venue
- Code of Conduct
- Contact
