### ISSUE TITLE
Please add details about accommodation (or make it obvious where such details are found)

### ISSUE THREAD

**Issue by ntoll** [PyconUK/2016.pyconuk.org#41]
What the title says.

**Comment by zeth** [comment]
We have been given permission to plagiarise this page: 
http://2015.djangocon.eu/welcome/accommodation/
It would be a good starting point at least.

**Comment by inglesp** [comment]
Closing in favour of https://github.com/PyconUK/pyconuk-2016-internaldocs/issues/68.  (I want to keep non-design stuff together in one place.)

**Comment by inglesp** [comment]
Closing in favour of https://github.com/PyconUK/pyconuk-2016-internaldocs/issues/68.  (I want to keep non-design stuff together in one place.)
