### ISSUE TITLE
Site looks "blocky" on mobile

### ISSUE THREAD

**Issue by inglesp** [PyconUK/2016.pyconuk.org#46]
Reported by @hjwp.

![screenshot_2016-04-26-13-27-23](https://cloud.githubusercontent.com/assets/28734/14823086/21841448-0bc9-11e6-9dea-6ffe974605ea.png)

**Comment by zeth** [comment]
What device is that? On my trusty Samsung Galaxy S3 on Firefox it looks nice and works well.

**Comment by inglesp** [comment]
I see the same as @hjwp with Chrome on my Fairphone 2.0.

**Comment by zeth** [comment]
Ok so now I see it, on Chrome on my phone I get it too. The widths don't work correctly in portrait mode, especially if you zoom/unzoom.

**Comment by hawkz** [comment]
Hmm odd, I'll look into it.
