### ISSUE TITLE
Have one date for Call for papers submissions

### ISSUE THREAD

**Issue by zeth** [PyconUK/2016.pyconuk.org#47]
Regarding the call for papers http://2016.pyconuk.org/cfp/

The date is not consistent. The first mention:

"Submissions are open until June 28th"

Then next time:

"The deadline for submissions is the end of Wednesday 15th June (UTC)."

I am assume the 15th June is the correct one?

**Comment by meshy** [comment]
Looks like this has been fixed in #48
