### ISSUE TITLE
Repo should contain unminimised CSS (or equivalent)

### ISSUE THREAD

**Issue by inglesp** [PyconUK/2016.pyconuk.org#53]
Ideally, there would be a step to generate the minimised CSS as part of `make build`, but that's less important.

**Comment by inglesp** [comment]
@hawkz, please can you add the raw CSS assets to the repo?

**Comment by inglesp** [comment]
Hi @hawkz -- can you give me a clue about what to do with these files?  When I try to run `lessc` or `lesscpy` over them, I get a syntax error.

**Comment by hawkz** [comment]
Hi

> Hi @hawkz https://github.com/hawkz -- can you give me a clue about what to do with these files? When I try to run lessc or lesscpy over them, I get a syntax error.,

What’s the error? - I’ll do my best.

**Comment by inglesp** [comment]
The error's in this gist: https://gist.github.com/inglesp/c18059635609eca3a4fe663095ad73df.

**Comment by inglesp** [comment]
Hi @hawkz, have you had the chance to look at this?

At the least, it'd be helpful to know exactly what command you've used to create the CSS output from the LESS input.

**Comment by hawkz** [comment]
@inglesp It comes first time for me, how are you setting up lessc (what version?)

**Comment by inglesp** [comment]
I've just reinstalled `lessc`, and it works fine.

`lesscpy` still barfs, but that doesn't matter so much.

**Comment by inglesp** [comment]
This is resolved.
