### ISSUE TITLE
Please add details of the kids day (if there is one)

### ISSUE THREAD

**Issue by ntoll** [PyconUK/2016.pyconuk.org#58]
Hi,

I've had two people ask me if there's going to be a kids day at this year's PyCon UK.

If there is, and given that families like to plan ahead because coordinating kids and stuff is hard if you need to travel across the country to Cardiff, please can details of this be put in an obvious place on the website.

Thanks!

**Comment by inglesp** [comment]
This was done a long time ago, closing.

(Next year let's put all issues into one repo!)
