### ISSUE TITLE
Can't see numbers typed into ticket amount input

### ISSUE THREAD

**Issue by 1stvamp** [PyconUK/2016.pyconuk.org#59]
On the [ticket package](http://2016.pyconuk.org/tickets/) I have typed the numeral `1` into the input field for _Self-funded ticket (3 days)_, but due to the width combined with my browsers font display (latest stable 64bit linux build of Chrome) I can't see the number.
![pyconukticketbug](https://cloud.githubusercontent.com/assets/35831/14848867/c61241bc-0c67-11e6-94be-8c66ea6d1178.png)

**Comment by inglesp** [comment]
I'll raise this with the ti.to support people.

**Comment by Lukasa** [comment]
I observe this effect in Chrome, Safari, and Firefox on OS X.

OS X 10.11.5 Beta
Chrome 50.0.2661.86
Safari 9.1.1 (11601.6.16)
Firefox 44.0.2

**Comment by inglesp** [comment]
Fixed by #60 from the nice man from ti.to.
