### ISSUE TITLE
Accessibility/good practice issue in header 

### ISSUE THREAD

**Issue by evildmp** [PyconUK/2016.pyconuk.org#63]
https://github.com/PyconUK/2016.pyconuk.org/blame/master/content/index.md#L5-L6 renders as two `<h1>`s with a line break between them:

```
        <h1>PyCon UK is your community-led</h1>

        <br/><h1>volunteer-run conference</h1>
```

Is there a better way of achieving the same visual effect?

**Comment by inglesp** [comment]
Good question!  This is one for @hawkz.

**Comment by inglesp** [comment]
@hawkz, any thoughts?

**Comment by hawkz** [comment]
Yeah, should be:

``` html
<h1>PyCon UK is your community-led<br/> volunteer-run conference</h1>
```

what's the rendering cause?

**Comment by hawkz** [comment]
This is best replaced with a wishlist for next year...
