### ISSUE TITLE
Request: CSS for a style on link anchors to create a nice button

### ISSUE THREAD

**Issue by evildmp** [PyconUK/2016.pyconuk.org#66]
@hawkz could we have something like:

```
a:link.button {
    color: white;
    background-color: blue;
    border-color: black;
    border-radius: 5px;
    }
```

... but nicer?

How would we set the class in MarkDown?

**Comment by inglesp** [comment]
I think the only way you can set a class on an element in Markdown is to embed an HTML element inside the Markdown.

An alternative would be to use reStructuredText.

**Comment by hawkz** [comment]
Of course. What's the goal here? More obvious links? in all cases or just in the main body of text?

**Comment by evildmp** [comment]
@hawkz actually, I notice that we have such a class as used in the Ticket button in the menu.

There's no way to apply a class except on a page in HTML format, is there (i.e. `.md` and `.rst` pages need not apply)?

**Comment by inglesp** [comment]
You can in Markdown, certainly, by embedding HTML directly in the `.md` file.

[It looks like you can work around it in reStructuredText too](http://docutils.sourceforge.net/docs/ref/rst/directives.html#raw-data-pass-through).
