### ISSUE TITLE
Talk length not stated on call for proposals page

### ISSUE THREAD

**Issue by emmagordon** [PyconUK/2016.pyconuk.org#84]
This would be really useful information for people contemplating possible talk proposals, as it helps guide topic choice/scope etc.

**Comment by Lukasa** [comment]
Yup, we 100% need this. We actually need better guidance than that: your slot will be _x_ minutes long, but you need to leave 5 minutes for handover, so your actual presentation slot will be _y_ minutes long, so if you want to do questions you'll only be able to present for _z_ minutes.

**Comment by evildmp** [comment]
@Lukasa @inglesp In that case I would like to revive the question I raised some weeks ago: how will we shape our talks days?

It's impossible to stipulate lengths of talks precisely without having made a decision on this. 

I propose to use http://conference-handbook.readthedocs.io/talks/timetable.html#plan-three-long-and-short-talks as the basis for Friday to Sunday, and http://conference-handbook.readthedocs.io/talks/timetable.html#plan-two-20-minute-slots as the basis for Thursday.

**Comment by Lukasa** [comment]
@evildmp Sounds reasonable to me.

**Comment by inglesp** [comment]
I've created https://github.com/PyconUK/pyconuk-2016-internaldocs/issues/92 to track putting the skeleton schedule together.

@evildmp: In the interim, could we add something to the CFP about talks being between twenty and forty minutes in length, and something about working with selected speakers to ensure that the scope of their talk matches the amount of time we allocate to them?

@Lukasa: Good point about whether length of talks includes questions.  See https://github.com/PyconUK/pyconuk-2016-internaldocs/pull/93 -- and feel free to add you own notes to this.

@emmagordon: Thanks for raising this -- and please do submit proposals to the CFP!

**Comment by inglesp** [comment]
This is now moot as the CFP has closed.  Closing.
